---
title: "Theory of Computing Notes"
subtitle: "Chapter 1: Introduction"
author: "Fraser Watt"
date: "2022-09-02"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
```

# Chapter Notes

## Sets and Notation

With set notation being represented with curly braces, an empty set would be ${ \{ \} }$, whilst a collection which only holds that empty set would be ${ \{\{ \}\} }$. Other important set notation:

- In / not in: ${ \in , \ \notin }$.
- ${x}$ as a subset of ${y}$: ${x \subset y}$.
- Natural numbers (positive integers): ${N}$.

Set logic might read something like this:

\[ \{ 2n | n \in N \} \]

The above would be read as *"*${2n}$*, given *${n}$ *is an element within the set of all natural numbers."*

**Fraser's Q:** Why does ${N - \{0\}}$ denote the set of all positive numbers, and not something like ${N \neq 0}$?

- This is because ${N}$ is a set, whilst $0$ is a number. So although $\{ 0 \}$ might only be a set with a length of one, $\{ 0 \} \neq 0$.
- ${N \neq 0}$ is true! But because a set is not a number. This is why we would say ${N - \{0\}}$ when we are talking about the set of all positive numbers.

## Joining Sets

- Intersection: Take elements common to both sets, written as ${A \ \cap \ B }$. This is like a SQL `JOIN`
- Union: New set includes all unique / distinct values of component sets, written as ${A \ \cup \ B }$. This is like a SQL `FULL JOIN`
- Cartesian Product: Takes elements from both sets and returns every possible combination from them, written as ${A \ \times \ B }$. This is like a SQL `CROSS JOIN`

## Relations

Throughout the book, there's a focus on using strings. Strings (words) are a collection of symbols where the symbols are all taken from a fixed alphabet. The alphabet can be thought of as a set!

- Length of word $w$ would be represented as $|w|$.
- Reverse of word $w$ would be represented as $w^R$ (palendrome).

The complement of a set is *everything that isn't in a given set*. So if ${A}$ was a set of all natural numbers, $A'= \{ n | n \notin N \}$. This is sort of like writing `!(yourLogicalStatement)` in Javascript, but ${!}$ in mathematical notation is factoral multiplication so wouldn't make sense here. 

### Transitive, Reflexive, and Symmetric relations.

- **Transitive:** Modular arithmetic (`%` in Python) useful to deconstruct this: if $4 \ \text{mod} \ 3  = 10 \ \text{mod} \ 3$ and $10 \ \text{mod} \ 3 = 13 \ \text{mod} \ 3$, then there is a transitive relation which says that $4 \ \text{mod} \ 3  = 13 \ \text{mod} \ 3$.

- **Symmetric:** If you have equivalence from $a \rightarrow b$ and another arrow from $b \rightarrow a$, then this is symmetric. Again, all or nothing — it is symmetric if for every arrow drawing equivalence, there is an equal and opposing relation backwards.

- **Reflexive:** If we are also going to use modular arithmetic here too, then we would be looking more like $10 \ \text{mod} \ 3 = 10 \ \text{mod} \ 3$.
  - If you add more arrows going to other items, it doesn’t matter — still reflexive! On the other hand, if you have two sets $\{a,b,c,d\}$, and you have arrows going from both $a$’s, $b$’s, & $c$’s — but no equivalence between $d_1$ and $d_2$ — this is not reflexive. It’s all or nothing!

- **Equivalence:** If it has a Transitive, Symmetric and Reflexive relation, then we can say it has an equivalence relation. I.e. $A=B$

# Exercises

**Exercise 1.1:** Give the notation for a set that contains only the page number of this exercise (page 9).

\[ R=\{ 9\} \]

**Exercise 1.2:** True or False

a) $\{2, 4, 5\} \subset \{ 2n \ | \ n \in N \}$
False

b) $\{e, i, t, c\} \subset \{a, ..., z\}$
True

c) $\bar{ \{2n\ | \ n \in N\} } = \{2n+1 \ | \ n \in N\}$
False

Originally had this as True, but did not consider that the complement of $\{2n\ | \ n \in N\}$ would also include non-natural numbers, whereas $\{ 2n \ | \ n \in N \}$ specifically states all members of the set would be natural.

d) $\{ 1, 2, 3, 4, 5 \} = \{1, ... , 5\}$
True

**Exercise 1.3:** Give a representation for the odd natural numbers.

My original answer to this was:

\[ \{ n | \frac{n}{2} \notin N \} \]

This is incorrect as (e.g.) $4.5$ would work; $\frac{4.5}{2}=2.25$ is not a neutral number. Instead we want to include a statement that $n$ is also a natural number, like so:

\[ \{ n | n \in N, \frac{n}{2} \notin N \} \] 

However, a more conventional way of writing it is:

\[ \{ 2n - 1\ | \ n \in N \} \]

Not only is this slightly more concise, all I've done in the first definition is define what my set is *not*, as opposed to defining what it *is*.


**Exercise 1.4:** For each of the strings $w$ below, exhibit both $|w|$ and $w^R$:

a) dooGyreV: $|a| = 8, \ a^R =$ VeryGood
b) kaerBAekaT: $|b| = 10, \ b^R =$ TakeABreak
c) kcanSAevaH: $|c| = 10, \ c^R =$ HaveASnack
d) ysaEooTsIsihT: $|d| = 13, \ d^R =$ ThisIsTooEasy

**Exercise 1.5:** Let $A= \{1, 2, ..., 100 \}$ and $B= \{ a, b, c, d \}$. How large is $A \times B$?

$N=400$

**Exercise 1.6:** Let $R = \{ a, b, c, d \}$ and $S = \{0, 1\}$. What is $R \times S$?

\[ \{ (a, 0), (b, 0), (c, 0), (d, 0), (a, 1), (b, 1), (c, 1), (d, 1) \} \]

**Exercise 1.7:** Define a relation $R$ on $N \times N$ by

\[ R= \{ (x, y) \ | \ x \in N, y \in N, x+y \ \text{is even} \} \]

Prove or disprove: $R$ is an equivalence relation:


* $R$ can be understood to mean "given $(x, y)$, $R$ is the set of all number pairs where $x$ and $y$ are both natural numbers ($N$), and the sum of $x+y$ is even."
* In order to prove $R$ is an equivalence relation, we need to prove that it is symmetric, reflexive and transitive.
  * It is symmetric as if $x+y$ is even, then so is $y+x$.
  * It is reflexive if for all $x \in N$, $(x, x) \in R$. As any $x$ would need to be an even natural number, this would satisfy the constraints that $y \in N, y \ \text{is even}$.
  * It is transitive if $(x, y) \in R, (y, z) \in R$, and $(x, z) \in R$. The addition of any two even numbers is always another even number, therefore any $(x, y)$ that satisfies the constraints of this set would also satisfy them in the case of $(y, z)$ and $(x, z)$.
* As this set satisfies symmetric, reflexive and transitive relations, we can prove $R$ is an equivalence relation.